<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="barista_robot">
    <xacro:property name="robot_name" value="$(arg robot_name)"/>

    <xacro:if value="${robot_name == 'rick'}">
        <xacro:property name="robot_color_rviz" value="blue"/>
        <xacro:property name="robot_color_gazebo" value="Gazebo/Blue"/>
    </xacro:if>
    <xacro:unless value="${robot_name == 'rick'}">
        <xacro:property name="robot_color_rviz" value="red"/>
        <xacro:property name="robot_color_gazebo" value="Gazebo/Red"/>
    </xacro:unless>

    <xacro:include filename="$(find barista_robot_description)/xacro/wheel.xacro" />
    <xacro:include filename="$(find barista_robot_description)/xacro/standoff.xacro" />
    <xacro:include filename="$(find barista_robot_description)/xacro/cup_holder_tray.xacro" />

    <xacro:arg  name="include_laser" default="true"/>


    <xacro:property name="body_radius" value="0.178"/>
    <xacro:property name="body_height" value="0.155"/>
    <xacro:property name="body_mass"   value= "5"/>

    <xacro:property name="wheel_separation" value = "0.3"/>


        
  <material name="red">
    <color rgba="1.0 0.0 0.0 1"/>
  </material>

  <material name="green_light">
    <color rgba="0.0 1.0 0.0 1"/>
  </material>

  <material name="green_dark">
    <color rgba="0.0 0.5 0.0 1"/>
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 1.0 1"/>
  </material>


  <material name="white">
      <color rgba="1.0 1.0 1.0 1"/>
  </material>

	<material name="black">
      <color rgba="0.0 0.0 0.0 1"/>
  </material>

  <link name="base_link">
  </link>

  <!-- Body -->
  <link name="chassis_link">
    <visual>
        <geometry>
            <cylinder radius="${body_radius}" length="${body_height}"/>
        </geometry>
		<material name="${robot_color_rviz}"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${body_mass}"/>
      <!-- <inertia ixx="0.04961541667" ixy="0" ixz="0" iyy="0.04961541667" iyz="0" izz="0.04961541667"/> -->
      <inertia  ixx="${body_mass*(3*body_radius*body_radius+body_height*body_height)/12}" ixy = "0" ixz = "0"
            iyy="${body_mass*(3*body_radius*body_radius+body_height*body_height)/12}" iyz = "0"
            izz="${body_mass*(body_radius*body_radius)/2}" />
    </inertial>
  </link>

   <gazebo reference="chassis_link">
      <material>${robot_color_gazebo}</material>
   </gazebo>

  <joint name="base_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${body_height/2}" />
    <parent link="base_link" />
    <child link="chassis_link" />
  </joint>

  <!-- standoff rods 1 -->
<xacro:standoff standoff_rod_name= "standoff_rod1_link"/>

<!-- standoff rods 2 -->
<xacro:standoff standoff_rod_name= "standoff_rod2_link"/>

<!-- standoff rods 3 -->
<xacro:standoff standoff_rod_name= "standoff_rod3_link"/>

<!-- standoff rods 4 -->
<xacro:standoff standoff_rod_name= "standoff_rod4_link"/>

	<gazebo reference="standoff_rod1_link">
      <material>Gazebo/white</material>
  </gazebo>

  <joint name="standoff_rod1_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${body_radius*0.618} ${body_radius*0.618} ${standoff_height/2+body_height/2}" />
    <parent link="chassis_link" />
    <child link="standoff_rod1_link" />
  </joint>


  <gazebo reference="standoff_rod2_link">
      <material>Gazebo/white</material>
  </gazebo>

  <joint name="standoff_rod2_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-${body_radius*0.618} ${body_radius*0.618} ${standoff_height/2+body_height/2}" />
    <parent link="chassis_link" />
    <child link="standoff_rod2_link" />
  </joint>

	<gazebo reference="standoff_rod3_link">
      <material>Gazebo/white</material>
  </gazebo>

  <joint name="standoff_rod3_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${body_radius*0.618} -${body_radius*0.618} ${standoff_height/2+body_height/2}" />
    <parent link="chassis_link" />
    <child link="standoff_rod3_link" />
  </joint>

	<gazebo reference="standoff_rod4_link">
      <material>Gazebo/white</material>
  </gazebo>

  <joint name="standoff_rod4_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-${body_radius*0.618} -${body_radius*0.618} ${standoff_height/2+body_height/2}" />
    <parent link="chassis_link" />
    <child link="standoff_rod4_link" />
  </joint>

<!-- Cup holder tray -->
<xacro:Cup_holder_tray    Cup_holder_tray_name="Cup_holder_tray_link"/>

  <gazebo reference="Cup_holder_tray_link">
      <material>${robot_color_gazebo}</material>
  </gazebo>

  <joint name="Cup_holder_tray_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${body_height/2+standoff_height+cup_holde_tray_height/2}" />
    <parent link="chassis_link" />
    <child link="Cup_holder_tray_link" />
  </joint>

  <!-- Wheel Left -->
<xacro:wheel    wheel_name="left_wheel"/>

 <!-- Wheel Right -->
<xacro:wheel    wheel_name="right_wheel"/>

  <gazebo reference="left_wheel">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
    <material>Gazebo/Black</material>
  </gazebo>


  <joint name="joint_left_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 ${wheel_separation/2} -0.06"/>
    <child link="left_wheel"/>
    <parent link="chassis_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <gazebo reference="right_wheel">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="joint_right_wheel" type="continuous">  
    <origin rpy="0 0 0" xyz="0 -${wheel_separation/2} -0.06"/>
    <child link="right_wheel"/>
    <parent link="chassis_link"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

    <!-- Caster Wheel Front -->
  <link name="front_yaw_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>          
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="0.0000008665583333" ixy="0" ixz="0" iyy="0.0000008665583333" iyz="0" izz="0.00000156645"/>
      </inertial>

  </link>

  <joint name="front_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.15 0 -0.0775" />
    <parent link="chassis_link" />
    <child link="front_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

    <gazebo reference="front_yaw_link">
        <material>Gazebo/Blue</material>
    </gazebo>


  <link name="front_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="0.0000008665583333" ixy="0" ixz="0" iyy="0.0000008665583333" iyz="0" izz="0.00000156645"/>
      </inertial>
  </link>

  <joint name="front_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_yaw_link" />
    <child link="front_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

    <gazebo reference="front_roll_link">
        <material>Gazebo/Red</material>
    </gazebo>


  <link name="front_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0177"/>
      </geometry>
      <material name="green_dark"/>
    </visual>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0177"/>
      </geometry>
    </collision>

    <inertial>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.00000125316" ixy="0" ixz="0" iyy="0.00000125316" iyz="0" izz="0.00000125316"/>
    </inertial>
  </link>

  <gazebo reference="front_pitch_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
    <material>Gazebo/Purple</material>
  </gazebo>

  <joint name="front_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_roll_link" />
    <child link="front_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

<!-- Caster Wheel Back -->
  <link name="back_yaw_link">
    <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="0.0000008665583333" ixy="0" ixz="0" iyy="0.0000008665583333" iyz="0" izz="0.00000156645"/>
      </inertial>
  </link>

  <joint name="back_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.15 0 -0.0775" />
    <parent link="chassis_link" />
    <child link="back_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

    <gazebo reference="back_yaw_link">
        <material>Gazebo/Blue</material>
    </gazebo>


  <link name="back_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.01" radius="0.0177"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="0.0000008665583333" ixy="0" ixz="0" iyy="0.0000008665583333" iyz="0" izz="0.00000156645"/>
      </inertial>
  </link>

  <joint name="back_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_yaw_link" />
    <child link="back_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

    <gazebo reference="back_roll_link">
        <material>Gazebo/Red</material>
    </gazebo>



  <link name="back_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0177"/>
      </geometry>
      <material name="green_light"/>
    </visual>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0177"/>
      </geometry>
    </collision>

    <inertial>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.00000125316" ixy="0" ixz="0" iyy="0.00000125316" iyz="0" izz="0.00000125316"/>
    </inertial>
  </link>

  <gazebo reference="back_pitch_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
    <material>Gazebo/Yellow</material>
  </gazebo>

  <joint name="back_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_roll_link" />
    <child link="back_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>



    <!-- JOINT PUBLISHER -->
  <gazebo>
    <plugin name="barisat_robot_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
          <namespace>/${robot_name}</namespace>
          <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>

      <joint_name>joint_left_wheel</joint_name>
      <joint_name>joint_right_wheel</joint_name>
      <joint_name>front_yaw_joint</joint_name>
      <joint_name>back_yaw_joint</joint_name>
      <joint_name>front_roll_joint</joint_name>
      <joint_name>back_roll_joint</joint_name>
      <joint_name>front_pitch_joint</joint_name>
      <joint_name>back_pitch_joint</joint_name>
      
    </plugin>
  </gazebo>

  <!-- Differential drive -->
  <gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
      <ros>
        <namespace>/${robot_name}</namespace>
        <remapping>/out:=cmd_vel</remapping>
      </ros>
      <!-- wheels -->
      <left_joint>joint_left_wheel</left_joint>
      <right_joint>joint_right_wheel</right_joint>

      <!-- kinematics -->
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius*2}</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>1.0</max_wheel_torque>
      <max_wheel_acceleration>2.0</max_wheel_acceleration>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>

      <odometry_frame>${robot_name}/odom</odometry_frame>
      <robot_base_frame>${robot_name}/base_link</robot_base_frame>

    </plugin>
  </gazebo>



<!-- Laser Sensor -->
<xacro:if value="$(arg include_laser)">
  <link name="laser_model_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://barista_robot_description/meshes/sensors/hokuyo_urg_04lx.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>

    <collision>
       <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://barista_robot_description/meshes/sensors/hokuyo_urg_04lx.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="6.066578520833334e-06" ixy="0" ixz="0" iyy="6.072950163333333e-06" iyz="0" izz="9.365128684166666e-06"/>
    </inertial>
  </link>

  <joint name="laser_scan_model_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.1 0.0 0.0775"/>
    <parent link="chassis_link"/>
    <child link="laser_model_link"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="laser_scan_frame">
    <origin rpy="0 0 0" xyz="0.1 0.0 0.0775"/>
  </link>

  <joint name="laser_scan_frame_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.05"/>
    <parent link="laser_model_link"/>
    <child link="laser_scan_frame"/>
  </joint>


  <gazebo reference="laser_scan_frame">
    <sensor name="sensor_ray" type="ray">
        <pose>0 0 0 0 0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>200</samples>
              <resolution>1.0</resolution>
              <min_angle>-3.14</min_angle>
              <max_angle>3.14</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.1</min>
            <max>5.0</max>
          </range>
        </ray>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>100.0</update_rate>
        <plugin name="laser_scan_node" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/${robot_name}</namespace>
            <remapping>~/out:=scan</remapping>
          </ros>
          <frame_name>${robot_name}/laser_scan_frame</frame_name>
          <output_type>sensor_msgs/LaserScan</output_type>
        </plugin>
    </sensor>
  </gazebo>
</xacro:if>

</robot>